# Runtime stage
FROM node:20-alpine AS base

ARG PORT
ARG JWT_SECRET
ARG JWT_REFRESH_SECRET

ARG DB_USER
ARG DB_PASSWORD
ARG DB_HOST
ARG DB_NAME
ARG DB_PORT
ARG MONGO_URI

ARG FRONTEND_URL
ARG SMTP_HOST
ARG SMTP_PORT
ARG SMTP_USER
ARG SMTP_PASS
ARG MAIL_FROM

ARG S3_ENDPOINT
ARG S3_REGION
ARG S3_ACCESS_KEY_ID
ARG S3_SECRET_ACCESS_KEY

ARG S3_BUCKET_NAME
ARG S3_CHUNK_SIZE
ARG S3_PRESIGNED_URL_EXPIRY

ARG CORS_ORIGIN

ARG TEMPORAL_HOST
ARG WORKER_CALLBACK_TOKEN
ARG BACKEND_INTERNAL_URL

ARG QUERY_SERVICE_URL

ARG QDRANT_URL

ENV PORT=${PORT}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_HOST=${DB_HOST}
ENV DB_NAME=${DB_NAME}
ENV DB_PORT=${DB_PORT}
ENV MONGO_URI=${MONGO_URI}

ENV FRONTEND_URL=${FRONTEND_URL}
ENV SMTP_HOST=${SMTP_HOST}
ENV SMTP_PORT=${SMTP_PORT}
ENV SMTP_USER=${SMTP_USER}
ENV SMTP_PASS=${SMTP_PASS}
ENV MAIL_FROM=${MAIL_FROM}

ENV S3_ENDPOINT=${S3_ENDPOINT}
ENV S3_REGION=${S3_REGION}
ENV S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
ENV S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}

ENV S3_BUCKET_NAME=${S3_BUCKET_NAME}
ENV S3_CHUNK_SIZE=${S3_CHUNK_SIZE}
ENV S3_PRESIGNED_URL_EXPIRY=${S3_PRESIGNED_URL_EXPIRY}

ENV CORS_ORIGIN=${CORS_ORIGIN}

ENV TEMPORAL_HOST=${TEMPORAL_HOST}
ENV WORKER_CALLBACK_TOKEN=${WORKER_CALLBACK_TOKEN}
ENV BACKEND_INTERNAL_URL=${BACKEND_INTERNAL_URL}

ENV QUERY_SERVICE_URL=${QUERY_SERVICE_URL}

ENV QDRANT_URL=${QDRANT_URL}
ENV NODE_ENV=production
FROM base AS runner
WORKDIR /app

# Copy package files from the app directory
COPY app/package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY app/ .

EXPOSE 3000

CMD ["node", "server.js"]
