name: VisionIndex CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint-secrets-tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: ./app

      - name: Run Linter
        run: npm run lint
        working-directory: ./app

      - name: Run Secret Scan (Gitleaks)
        run: |
          curl -sL https://github.com/zricethezav/gitleaks/releases/download/v8.16.1/gitleaks_8.16.1_linux_x64.tar.gz | tar xz
          ./gitleaks detect --redact --exit-code=1

      - name: Run Tests (Local Mongo)
        env:
          MONGO_URI: mongodb://localhost:27017/ci_testdb
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          NODE_ENV: test
        run: npm test
        working-directory: ./app

      # - name: Force terminate leftover processes
      #   if: always()
      #   run: |
      #     # Use pkill with SIGKILL to forcefully terminate any Node.js processes
      #     # The -9 flag corresponds to the SIGKILL signal
      #     pkill -9 -f node || true