name: VisionIndex CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: ./app

      - name: Run Linter
        run: npm run lint
        working-directory: ./app

      - name: Run Secret Scan (Gitleaks)
        run: |
          curl -sL https://github.com/zricethezav/gitleaks/releases/download/v8.16.1/gitleaks_8.16.1_linux_x64.tar.gz | tar xz
          ./gitleaks detect --redact --exit-code=1
